import type {
  InterfacePattern,
  InterfacePatternCatalog,
  SourceLocation,
  SystemFinding,
} from '@nas/contracts';

/**
 * The interface anti-pattern catalog: 46 recurring interface failures a
 * reviewer grades a product mockup, generated site, or design against.
 *
 * Each entry declares its signal — a specific AI-generation marker
 * (`ai_generated_marker`) or a general quality failure — how it can be
 * detected, the anti-slop dimension it grades into, and a remediation. A hit
 * becomes a `DS_INTERFACE_PATTERN` SystemFinding via `interfacePatternFinding`,
 * so reviews cite `#20 antipattern.gradient-text`, never a vibe. Catalog
 * integrity (unique ids, contiguous numbering) is enforced by
 * `validateInterfacePatternCatalog` in @nas/contracts and by test.
 */

type Entry = [
  number,
  string, // id slug (antipattern.<slug>)
  string, // name
  InterfacePattern['category'],
  InterfacePattern['signal'],
  InterfacePattern['detection'],
  InterfacePattern['dimension'],
  InterfacePattern['defaultSeverity'],
  string, // description
  string, // remediation
];

const AI = 'ai_generated_marker' as const;
const GEN = 'general_quality_failure' as const;

const ENTRIES: Entry[] = [
  // ── Visual details ─────────────────────────────────────────────────────────
  [
    1,
    'border-accent-on-rounded',
    'Border accent on rounded element',
    'visual_details',
    AI,
    'static_analysis',
    'design_consistency',
    'moderate',
    'A thick accent border conflicts with rounded corners.',
    'Pick one depth/emphasis language: either the radius or the accent border, driven by tokens.',
  ],
  [
    2,
    'glassmorphism-everywhere',
    'Glassmorphism everywhere',
    'visual_details',
    AI,
    'rendered_page',
    'design_originality',
    'serious',
    'Glass cards, blur, and glow effects are applied without a functional reason.',
    'Remove blur/glow that serves no function; use flat token surfaces and hairline borders.',
  ],
  [
    3,
    'side-tab-accent-border',
    'Side-tab accent border',
    'visual_details',
    AI,
    'static_analysis',
    'design_originality',
    'moderate',
    'A rounded card uses a thick colored stripe on one side.',
    'Communicate state with the status vocabulary (label + tone), not a decorative stripe.',
  ],
  [
    4,
    'hairline-border-wide-shadow',
    'Hairline border with wide shadow',
    'visual_details',
    GEN,
    'static_analysis',
    'design_consistency',
    'moderate',
    'A thin border and large diffuse shadow create conflicting depth cues.',
    'Choose one elevation cue per surface; take shadow values from the shadow tokens.',
  ],
  [
    5,
    'repeating-gradient-stripes',
    'Repeating-gradient stripes',
    'visual_details',
    AI,
    'static_analysis',
    'design_originality',
    'moderate',
    'Generated stripes are used as arbitrary surface decoration.',
    'Delete decorative gradients; hierarchy comes from type and space, not surface noise.',
  ],
  [
    6,
    'extreme-border-radius',
    'Extreme border radius on cards',
    'visual_details',
    AI,
    'static_analysis',
    'design_consistency',
    'moderate',
    'Small cards and inputs are rounded into indistinct blobs.',
    'Use the closed radius scale; radius must scale down with element size.',
  ],
  [
    7,
    'amateur-hand-drawn-svg',
    'Amateurish hand-drawn SVG',
    'visual_details',
    AI,
    'manual_review',
    'design_originality',
    'serious',
    'Crude programmatic illustrations substitute for professional assets.',
    'Remove the illustration entirely or commission a real asset; no filler artwork.',
  ],
  // ── Typography ─────────────────────────────────────────────────────────────
  [
    8,
    'flat-type-hierarchy',
    'Flat type hierarchy',
    'typography',
    GEN,
    'static_analysis',
    'design_consistency',
    'serious',
    'Headings, subheadings, and body text have nearly identical sizes.',
    'Apply the type scale so each level is visibly distinct in size, weight, or color.',
  ],
  [
    9,
    'icon-tile-above-heading',
    'Icon tile stacked above heading',
    'typography',
    AI,
    'rendered_page',
    'design_originality',
    'moderate',
    'Every feature card uses the same rounded icon box above its title.',
    'Drop the icon tiles unless each icon carries real meaning; vary card anatomy by content.',
  ],
  [
    10,
    'italic-serif-display',
    'Italic serif display headline',
    'typography',
    AI,
    'static_analysis',
    'design_originality',
    'minor',
    'An oversized italic serif headline serves as a generic signal of taste.',
    'Set headlines in the system type stack with deliberate weight/tracking instead.',
  ],
  [
    11,
    'hero-eyebrow-pill',
    'Hero eyebrow or pill chip',
    'typography',
    AI,
    'rendered_page',
    'design_originality',
    'minor',
    'A small uppercase label or pill appears immediately above the main headline.',
    'Keep an eyebrow only when it adds navigation context; delete reflexive chips.',
  ],
  [
    12,
    'repeated-section-kickers',
    'Repeated section kicker labels',
    'typography',
    AI,
    'rendered_page',
    'design_originality',
    'moderate',
    'Every section begins with another tiny, uppercase, letter-spaced label.',
    'Use kickers sparingly; identical kickers on every section are template residue.',
  ],
  [
    13,
    'oversized-hero-headline',
    'Oversized hero headline',
    'typography',
    AI,
    'rendered_page',
    'design_consistency',
    'moderate',
    'A full sentence is enlarged until it consumes most of the opening viewport.',
    'Size the headline to the message; the viewport should also answer what the product does.',
  ],
  [
    14,
    'crushed-letter-spacing',
    'Crushed letter spacing',
    'typography',
    GEN,
    'static_analysis',
    'accessibility',
    'serious',
    'Display text is tightened enough to damage legibility.',
    'Limit negative tracking to the token value; verify legibility at render size.',
  ],
  [
    15,
    'overused-font',
    'Overused font',
    'typography',
    AI,
    'static_analysis',
    'design_originality',
    'minor',
    'The design defaults to Inter, Geist, Space Grotesk, or Instrument Serif.',
    'Choose type deliberately for the product voice — or own the default explicitly.',
  ],
  [
    16,
    'single-font-everything',
    'Single font for everything',
    'typography',
    GEN,
    'static_analysis',
    'design_consistency',
    'minor',
    'Headings, body copy, labels, and controls use one font family without meaningful contrast.',
    'Create contrast through the scale (size/weight/case) or add a deliberate second family.',
  ],
  [
    17,
    'all-caps-body',
    'All-caps body text',
    'typography',
    GEN,
    'static_analysis',
    'accessibility',
    'serious',
    'Long passages are rendered in uppercase, reducing readability.',
    'Reserve uppercase for short labels; body copy stays sentence case.',
  ],
  // ── Color and contrast ─────────────────────────────────────────────────────
  [
    18,
    'ai-color-palette',
    'AI color palette',
    'color_contrast',
    AI,
    'static_analysis',
    'design_originality',
    'serious',
    'Purple or violet gradients and cyan-on-dark dominate the interface.',
    'Derive the palette from the product; restrained neutrals plus one deliberate accent.',
  ],
  [
    19,
    'dark-mode-glow',
    'Dark mode with glowing accents',
    'color_contrast',
    AI,
    'static_analysis',
    'design_originality',
    'serious',
    'Colored shadows and neon glows are applied to a dark background by default.',
    'Remove colored glows; dark surfaces use the same token shadows as light ones.',
  ],
  [
    20,
    'gradient-text',
    'Gradient text',
    'color_contrast',
    AI,
    'static_analysis',
    'design_originality',
    'moderate',
    'Decorative gradients are applied to headlines, metrics, or other text.',
    'Text renders in a single token color; emphasis comes from weight and size.',
  ],
  [
    21,
    'gray-on-colored',
    'Gray text on colored background',
    'color_contrast',
    GEN,
    'rendered_page',
    'accessibility',
    'serious',
    'Neutral gray text appears washed out against a colored surface.',
    'Pick a foreground tested against the actual surface color at 4.5:1.',
  ],
  [
    22,
    'cream-beige-default',
    'Cream or beige palette',
    'color_contrast',
    AI,
    'static_analysis',
    'design_originality',
    'minor',
    'Warm off-white becomes the automatic choice for making a product appear refined.',
    'Choose surface temperature for the product context, not as a taste shortcut.',
  ],
  // ── Layout and spacing ─────────────────────────────────────────────────────
  [
    23,
    'hero-metric-layout',
    'Hero metric layout',
    'layout_spacing',
    AI,
    'rendered_page',
    'design_originality',
    'moderate',
    'One large metric, a small label, and several supporting statistics form a generic opening section.',
    'Open with the user’s dominant question; show a metric only when it changes a decision.',
  ],
  [
    24,
    'identical-card-grids',
    'Identical card grids',
    'layout_spacing',
    AI,
    'rendered_page',
    'design_originality',
    'moderate',
    'Repeated, equally sized cards use the same icon, heading, and short-description structure.',
    'Let content dictate card anatomy; merge or remove cards that exist to fill a grid.',
  ],
  [
    25,
    'monotonous-spacing',
    'Monotonous spacing',
    'layout_spacing',
    GEN,
    'static_analysis',
    'design_consistency',
    'moderate',
    'The same spacing value is used everywhere, eliminating hierarchy and rhythm.',
    'Use the spacing scale intentionally: tighter within groups, looser between them.',
  ],
  [
    26,
    'nested-cards',
    'Nested cards',
    'layout_spacing',
    AI,
    'rendered_page',
    'design_consistency',
    'moderate',
    'Cards are placed inside other cards, creating excessive containers and visual depth.',
    'Flatten: one bordered surface per topic; inner structure uses spacing, not more boxes.',
  ],
  [
    27,
    'numbered-section-markers',
    'Numbered section markers',
    'layout_spacing',
    AI,
    'rendered_page',
    'design_originality',
    'minor',
    'Sections are labeled 01, 02, and 03 even when they do not represent a sequence.',
    'Number only true sequences; otherwise use meaningful section titles.',
  ],
  [
    28,
    'line-length-too-long',
    'Line length too long',
    'layout_spacing',
    GEN,
    'rendered_page',
    'accessibility',
    'moderate',
    'Text lines exceed a comfortable reading width.',
    'Cap the measure with a token (e.g. layout.measure-max ≈ 60ch).',
  ],
  [
    29,
    'content-overflow',
    'Content overflowing its container',
    'layout_spacing',
    GEN,
    'rendered_page',
    'responsive_quality',
    'serious',
    'Text or interface elements spill outside their assigned boundaries.',
    'Fix the box model; test at every breakpoint with real content lengths.',
  ],
  [
    30,
    'clipped-positioned-child',
    'Positioned child clipped by overflow container',
    'layout_spacing',
    GEN,
    'rendered_page',
    'responsive_quality',
    'serious',
    'Menus, tooltips, or popovers are cut off by a parent container.',
    'Render overlays in a top-layer/portal or fix the ancestor overflow context.',
  ],
  // ── Motion ─────────────────────────────────────────────────────────────────
  [
    31,
    'bounce-elastic-easing',
    'Bounce or elastic easing',
    'motion',
    AI,
    'static_analysis',
    'interaction_quality',
    'moderate',
    'Dialogs, cards, and controls spring or overshoot without a physical reason.',
    'Use the token easing curve; motion is feedback, not decoration.',
  ],
  [
    32,
    'layout-property-animation',
    'Layout property animation',
    'motion',
    GEN,
    'static_analysis',
    'interaction_quality',
    'serious',
    'Width, height, padding, or margins are animated, causing unstable layout movement.',
    'Animate transform/opacity only; never animate properties that reflow layout.',
  ],
  [
    33,
    'image-hover-transform',
    'Image hover transform',
    'motion',
    AI,
    'static_analysis',
    'interaction_quality',
    'minor',
    'Images automatically scale or rotate when hovered.',
    'Remove hover transforms that signal nothing; hover states belong to interactive elements.',
  ],
  // ── Copy ───────────────────────────────────────────────────────────────────
  [
    34,
    'em-dash-overuse',
    'Em-dash overuse',
    'copy',
    AI,
    'manual_review',
    'design_originality',
    'minor',
    'Body copy repeatedly uses em dashes as a predictable synthetic writing cadence.',
    'Rewrite with varied sentence structure; keep em dashes rare and deliberate.',
  ],
  [
    35,
    'marketing-buzzwords',
    'Marketing buzzwords',
    'copy',
    AI,
    'manual_review',
    'design_originality',
    'moderate',
    'Copy relies on terms such as streamline, empower, supercharge, and world-class.',
    'Say specifically what the product does and for whom; delete the adjectives.',
  ],
  [
    36,
    'aphoristic-cadence',
    'Aphoristic-cadence copy',
    'copy',
    AI,
    'manual_review',
    'design_originality',
    'moderate',
    'Sections repeatedly end with short manufactured contrasts such as “Not a feature. A platform.”',
    'State the actual claim once, in plain sentences, with evidence.',
  ],
  [
    37,
    'theater-framing',
    'Theater-framing copy',
    'copy',
    AI,
    'manual_review',
    'design_originality',
    'moderate',
    'Ordinary practices are dismissed as “growth theater,” “security theater,” or similar performative framing.',
    'Argue the substantive difference instead of naming a theater.',
  ],
  // ── Imagery ────────────────────────────────────────────────────────────────
  [
    38,
    'broken-placeholder-image',
    'Broken or placeholder image',
    'imagery',
    GEN,
    'rendered_page',
    'product_correctness',
    'serious',
    'Image elements contain empty, missing, or placeholder source values.',
    'Ship real assets or remove the element; placeholders never reach review as product truth.',
  ],
  // ── General quality ────────────────────────────────────────────────────────
  [
    39,
    'cramped-padding',
    'Cramped padding',
    'general_quality',
    GEN,
    'rendered_page',
    'design_consistency',
    'moderate',
    'Text sits too close to a container’s border.',
    'Pad containers from the spacing scale; verify at the smallest breakpoint.',
  ],
  [
    40,
    'body-text-touching-edge',
    'Body text touching viewport edge',
    'general_quality',
    GEN,
    'rendered_page',
    'responsive_quality',
    'serious',
    'Paragraphs run against the edge of the screen without horizontal padding.',
    'Give the content column horizontal padding at every breakpoint.',
  ],
  [
    41,
    'justified-text',
    'Justified text',
    'general_quality',
    GEN,
    'static_analysis',
    'accessibility',
    'moderate',
    'Browser-rendered paragraphs create uneven gaps and rivers of whitespace.',
    'Use left-aligned (start-aligned) body text on the web.',
  ],
  [
    42,
    'low-contrast-text',
    'Low-contrast text',
    'general_quality',
    GEN,
    'rendered_page',
    'accessibility',
    'critical',
    'Text fails accepted accessibility contrast standards.',
    'Meet WCAG 2.2 AA (4.5:1 body, 3:1 large/UI) in every theme; test the real pairs.',
  ],
  [
    43,
    'skipped-heading-level',
    'Skipped heading level',
    'general_quality',
    GEN,
    'rendered_page',
    'accessibility',
    'serious',
    'The document jumps between heading levels, such as from H1 directly to H3.',
    'Keep a contiguous heading outline; style with classes, not heading levels.',
  ],
  [
    44,
    'tight-line-height',
    'Tight line height',
    'general_quality',
    GEN,
    'static_analysis',
    'accessibility',
    'moderate',
    'Multiline text lacks enough vertical separation for comfortable reading.',
    'Body copy uses the normal leading token (≈1.5); headings may tighten, body never.',
  ],
  [
    45,
    'tiny-body-text',
    'Tiny body text',
    'general_quality',
    GEN,
    'static_analysis',
    'accessibility',
    'serious',
    'Regular or supporting copy is rendered below a practical reading size.',
    'Keep body and supporting copy on the type scale; nothing under the smallest step.',
  ],
  [
    46,
    'wide-tracking-body',
    'Wide letter spacing on body text',
    'general_quality',
    GEN,
    'static_analysis',
    'accessibility',
    'moderate',
    'Excessive tracking disrupts normal word and character recognition.',
    'Reserve wide tracking for short uppercase labels; body text uses default tracking.',
  ],
];

export const INTERFACE_PATTERN_CATALOG: InterfacePatternCatalog = {
  schemaVersion: 1,
  version: '1.0.0',
  patterns: ENTRIES.map(
    ([
      number,
      slug,
      name,
      category,
      signal,
      detection,
      dimension,
      defaultSeverity,
      description,
      remediation,
    ]) => ({
      id: `antipattern.${slug}`,
      number,
      name,
      category,
      signal,
      detection,
      dimension,
      defaultSeverity,
      description,
      remediation,
    }),
  ),
};

const byId = new Map(INTERFACE_PATTERN_CATALOG.patterns.map((p) => [p.id, p]));
const byNumber = new Map(INTERFACE_PATTERN_CATALOG.patterns.map((p) => [p.number, p]));

/** Look up a catalog pattern by id (`antipattern.gradient-text`) or number (20). */
export function interfacePattern(ref: string | number): InterfacePattern {
  const pattern = typeof ref === 'number' ? byNumber.get(ref) : byId.get(ref);
  if (!pattern) {
    throw new Error(`unknown interface anti-pattern "${ref}" — cite a catalog entry, not a vibe`);
  }
  return pattern;
}

/**
 * Turn an observed catalog hit into a structured system finding. The finding
 * carries the pattern's dimension and default severity, so a serious+ hit
 * fails that dimension through the ordinary anti-slop gate — no new scoring
 * path, no aggregate.
 */
export function interfacePatternFinding(
  ref: string | number,
  location: SourceLocation,
  observed: string,
): SystemFinding {
  const pattern = interfacePattern(ref);
  return {
    code: 'DS_INTERFACE_PATTERN',
    severity: pattern.defaultSeverity,
    dimension: pattern.dimension,
    location,
    rationale: `#${pattern.number} ${pattern.name} (${pattern.signal === 'ai_generated_marker' ? 'AI-generation marker' : 'quality failure'}): ${observed}`,
    remediation: pattern.remediation,
    patternId: pattern.id,
    evidenceIds: [],
  };
}
