import type { DesignSystemRegistry, DesignTokenDef } from '@nas/contracts';
import { breakpoints, darkStatus, darkTheme, lightStatus, lightTheme, spacing } from './tokens.js';

/**
 * The design-system registry: the machine-readable inventory of the ACTUAL
 * system — every token, component, pattern, principle, accessibility rule,
 * owner, and exception that exists in this repository today.
 *
 * This is data about real code, kept next to that code. Color values are
 * imported from tokens.ts (the contrast-tested source of truth), never
 * re-typed. registry.test.ts enforces the other direction of sync: every
 * cssVariable listed here must exist in tokens.css with the exact same value,
 * every custom property in tokens.css must be claimed by exactly one token,
 * and every component exported from @nas/ui must have a registry entry.
 * Referential integrity is enforced by validateDesignSystemRegistry from
 * @nas/contracts — in tests and again, live, on the control plane's System view.
 */

/* ── Token builders (values imported, not duplicated) ───────────────────────── */

function themedColor(
  id: string,
  cssVariable: string,
  description: string,
  pick: (theme: typeof lightTheme) => string,
): DesignTokenDef {
  return {
    id,
    tier: 'semantic',
    category: 'color',
    description,
    valueByTheme: { light: pick(lightTheme), dark: pick(darkTheme) },
    cssVariable,
  };
}

function statusColor(
  tone: keyof typeof lightStatus,
  part: 'fg' | 'bg',
  description: string,
): DesignTokenDef {
  return {
    id: `status.${tone}.${part}`,
    tier: 'semantic',
    category: 'color',
    description,
    valueByTheme: { light: lightStatus[tone][part], dark: darkStatus[tone][part] },
    cssVariable: `--nas-${tone}-${part}`,
  };
}

const spacingTokens: DesignTokenDef[] = spacing.map((px, step) => ({
  id: `space.${step}`,
  tier: 'primitive',
  category: 'spacing',
  description: step === 0 ? 'Zero spacing.' : `Spacing scale step ${step} (${px}px).`,
  value: px === 0 ? '0' : `${px}px`,
  // Steps 1–11 are mirrored as CSS custom properties; 0 and 12 are TS-only.
  ...(step >= 1 && step <= 11 ? { cssVariable: `--nas-space-${step}` } : {}),
}));

const breakpointTokens: DesignTokenDef[] = (
  Object.entries(breakpoints) as [keyof typeof breakpoints, number][]
).map(([name, px]) => ({
  id: `breakpoint.${name}`,
  tier: 'primitive',
  category: 'breakpoint',
  description: `Min-width breakpoint: ${name} (${px}px). Mobile-first.`,
  value: `${px}px`,
}));

const primitive = (
  id: string,
  category: DesignTokenDef['category'],
  cssVariable: string,
  value: string,
  description: string,
): DesignTokenDef => ({ id, tier: 'primitive', category, description, value, cssVariable });

const semantic = (
  id: string,
  category: DesignTokenDef['category'],
  cssVariable: string,
  value: string,
  description: string,
): DesignTokenDef => ({ id, tier: 'semantic', category, description, value, cssVariable });

const tokens: DesignTokenDef[] = [
  // Semantic colors (values from tokens.ts, contrast-tested in tokens.test.ts).
  themedColor('color.bg', '--nas-bg', 'App background.', (t) => t.bg),
  themedColor('color.surface', '--nas-surface', 'Card / panel surface.', (t) => t.surface),
  themedColor('color.surface-2', '--nas-surface-2', 'Raised / hover surface.', (t) => t.surface2),
  themedColor('color.border', '--nas-border', 'Hairline borders and dividers.', (t) => t.border),
  themedColor('color.text', '--nas-text', 'Primary text.', (t) => t.text),
  themedColor(
    'color.text-secondary',
    '--nas-text-secondary',
    'Supporting text; still meets 4.5:1.',
    (t) => t.textSecondary,
  ),
  themedColor(
    'color.text-tertiary',
    '--nas-text-tertiary',
    'De-emphasized labels (eyebrows, captions).',
    (t) => t.textTertiary,
  ),
  themedColor(
    'color.accent',
    '--nas-accent',
    'THE single action accent (mint). Reserved for the one primary action.',
    (t) => t.accent,
  ),
  themedColor(
    'color.accent-hover',
    '--nas-accent-hover',
    'Hover shade of the action accent.',
    (t) => t.accentHover,
  ),
  themedColor(
    'color.on-accent',
    '--nas-on-accent',
    'Text/icon color on the accent fill (4.5:1 on accent).',
    (t) => t.onAccent,
  ),
  themedColor('color.focus', '--nas-focus', 'Focus-ring color.', (t) => t.focus),
  // Status colors — always paired with a text label or symbol, never color alone.
  statusColor('success', 'fg', 'Success foreground (on its tinted background).'),
  statusColor('success', 'bg', 'Success tinted background.'),
  statusColor('warning', 'fg', 'Warning foreground.'),
  statusColor('warning', 'bg', 'Warning tinted background.'),
  statusColor('danger', 'fg', 'Danger/blocked foreground.'),
  statusColor('danger', 'bg', 'Danger/blocked tinted background.'),
  statusColor('info', 'fg', 'Informational foreground.'),
  statusColor('info', 'bg', 'Informational tinted background.'),
  statusColor('neutral', 'fg', 'Neutral/not-tested foreground.'),
  statusColor('neutral', 'bg', 'Neutral/not-tested tinted background.'),
  // Typography.
  primitive(
    'type.family.sans',
    'typography',
    '--nas-font-sans',
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Inter, Roboto, Helvetica, Arial, sans-serif",
    'UI text stack (system fonts; no webfont payload).',
  ),
  primitive(
    'type.family.mono',
    'typography',
    '--nas-font-mono',
    "ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, monospace",
    'Monospace stack for digests, ids, and code.',
  ),
  primitive('type.size.xs', 'typography', '--nas-text-xs', '0.75rem', 'Captions, badges.'),
  primitive('type.size.sm', 'typography', '--nas-text-sm', '0.8125rem', 'Secondary text.'),
  primitive('type.size.base', 'typography', '--nas-text-base', '0.9375rem', 'Body text.'),
  primitive('type.size.lg', 'typography', '--nas-text-lg', '1.0625rem', 'Card titles.'),
  primitive('type.size.xl', 'typography', '--nas-text-xl', '1.375rem', 'Section titles.'),
  primitive('type.size.2xl', 'typography', '--nas-text-2xl', '1.75rem', 'Page titles.'),
  primitive('type.size.3xl', 'typography', '--nas-text-3xl', '2.25rem', 'Hero numerals.'),
  primitive('type.weight.regular', 'typography', '--nas-weight-regular', '400', 'Body weight.'),
  primitive('type.weight.medium', 'typography', '--nas-weight-medium', '500', 'Labels, buttons.'),
  primitive(
    'type.weight.semibold',
    'typography',
    '--nas-weight-semibold',
    '600',
    'Titles; the heaviest weight in the system.',
  ),
  primitive('type.leading.tight', 'typography', '--nas-leading-tight', '1.2', 'Headings.'),
  primitive('type.leading.normal', 'typography', '--nas-leading-normal', '1.5', 'Body copy.'),
  primitive(
    'type.tracking.tight',
    'typography',
    '--nas-tracking-tight',
    '-0.01em',
    'Large titles pull in slightly.',
  ),
  primitive(
    'type.tracking.wide',
    'typography',
    '--nas-tracking-wide',
    '0.06em',
    'Uppercase eyebrows open up.',
  ),
  // Spacing (closed scale — arbitrary spacing is a slop tell).
  ...spacingTokens,
  // Radii, borders, shadows, motion.
  primitive('radius.sm', 'radius', '--nas-radius-sm', '6px', 'Focus-ring corners, small chips.'),
  primitive('radius.md', 'radius', '--nas-radius-md', '10px', 'Buttons, nav links.'),
  primitive('radius.lg', 'radius', '--nas-radius-lg', '14px', 'Cards and panels.'),
  primitive('radius.full', 'radius', '--nas-radius-full', '999px', 'Pills and badges.'),
  primitive('border.width', 'border', '--nas-border-width', '1px', 'Hairline border width.'),
  {
    id: 'shadow.sm',
    tier: 'semantic',
    category: 'shadow',
    description: 'Resting card elevation (deeper in dark theme).',
    valueByTheme: {
      light: '0 1px 2px rgba(0, 0, 0, 0.06)',
      dark: '0 1px 2px rgba(0, 0, 0, 0.4)',
    },
    cssVariable: '--nas-shadow-sm',
  },
  {
    id: 'shadow.md',
    tier: 'semantic',
    category: 'shadow',
    description: 'Raised elevation for overlays.',
    valueByTheme: {
      light: '0 4px 16px rgba(0, 0, 0, 0.08)',
      dark: '0 4px 16px rgba(0, 0, 0, 0.5)',
    },
    cssVariable: '--nas-shadow-md',
  },
  primitive('motion.fast', 'motion', '--nas-motion-fast', '120ms', 'Hover/press feedback.'),
  primitive('motion.normal', 'motion', '--nas-motion-normal', '200ms', 'Panel transitions.'),
  primitive(
    'motion.ease',
    'motion',
    '--nas-ease',
    'cubic-bezier(0.2, 0, 0, 1)',
    'The single easing curve.',
  ),
  // Interaction sizes + states.
  semantic(
    'size.control',
    'size',
    '--nas-size-control',
    '40px',
    'Minimum interactive control height (touch target).',
  ),
  semantic(
    'size.control-compact',
    'size',
    '--nas-size-control-compact',
    '36px',
    'Reduced control height for secondary chrome controls only.',
  ),
  semantic(
    'size.card-min',
    'size',
    '--nas-size-card-min',
    '280px',
    'Minimum card width in responsive auto-fit grids.',
  ),
  semantic(
    'size.label-min',
    'size',
    '--nas-size-label-min',
    '120px',
    'Minimum label column width in definition lists.',
  ),
  semantic(
    'size.focus-ring-width',
    'size',
    '--nas-focus-ring-width',
    '2px',
    'Focus-ring outline width.',
  ),
  semantic(
    'size.focus-ring-offset',
    'size',
    '--nas-focus-ring-offset',
    '2px',
    'Focus-ring outline offset.',
  ),
  semantic(
    'opacity.disabled',
    'opacity',
    '--nas-opacity-disabled',
    '0.5',
    'Disabled-control opacity (paired with cursor + aria state, never alone).',
  ),
  // Layout.
  semantic('layout.content-max', 'layout', '--nas-content-max', '1120px', 'Main content column.'),
  semantic(
    'layout.measure-max',
    'layout',
    '--nas-measure-max',
    '60ch',
    'Maximum reading measure for descriptions.',
  ),
  semantic('layout.sidebar-width', 'layout', '--nas-sidebar-width', '240px', 'Desktop sidebar.'),
  semantic('layout.z-nav', 'layout', '--nas-z-nav', '100', 'Navigation stacking layer.'),
  semantic('layout.z-overlay', 'layout', '--nas-z-overlay', '200', 'Overlay stacking layer.'),
  // Breakpoints (primitive; CSS media queries cannot read custom properties —
  // see exception.breakpoint-media-query).
  ...breakpointTokens,
];

/* ── The registry ───────────────────────────────────────────────────────────── */

export const designSystemRegistry: DesignSystemRegistry = {
  schemaVersion: 1,
  name: 'No AI Slop Design System',
  version: '1.1.0',

  principles: [
    {
      id: 'principle.radical-clarity',
      name: 'Radical clarity',
      statement: 'Every screen answers one dominant question a user actually has.',
      rationale:
        'The control plane exists to answer "can I trust this change?" — decoration that does not serve that question is removed.',
    },
    {
      id: 'principle.one-primary-action',
      name: 'One primary action',
      statement: 'Each screen shows at most one primary (accent) action.',
      rationale: 'Competing primary actions dilute the decision the screen exists to support.',
    },
    {
      id: 'principle.hierarchy-without-decoration',
      name: 'Hierarchy through type and space',
      statement: 'Visual hierarchy comes from the type scale and spacing scale, not decoration.',
      rationale:
        'Gradients, glass, and glow are generic AI-slop tells; restrained neutrals keep evidence legible.',
    },
    {
      id: 'principle.closed-scales',
      name: 'Closed scales',
      statement:
        'Type, spacing, radius, and motion values come from the token scales; arbitrary values are findings.',
      rationale: 'Arbitrary values are how systems fragment one commit at a time.',
    },
    {
      id: 'principle.status-not-color-alone',
      name: 'Status is never color alone',
      statement: 'Every status renders a text label and/or symbol alongside its tone.',
      rationale: 'WCAG 1.4.1, and color-blind operators must read release verdicts correctly.',
    },
    {
      id: 'principle.explicit-states',
      name: 'Explicit states',
      statement:
        'Loading, empty, error, and blocked states are designed explicitly — never a blank void.',
      rationale: 'An undesigned state is an undesigned decision left to chance in production.',
    },
    {
      id: 'principle.progressive-disclosure',
      name: 'Progressive disclosure',
      statement:
        'Primary workflows show conclusions; raw detail (digests, full lists) sits one intentional step deeper.',
      rationale: 'Operators need answers first, reconstruction second — but always both.',
    },
    {
      id: 'principle.evidence-backed',
      name: 'Evidence-backed claims',
      statement: 'Interface claims about builds, checks, or decisions trace to sealed evidence.',
      rationale: 'The product exists to make unproven claims impossible to miss.',
    },
  ],

  owners: [
    {
      id: 'owner.design-systems',
      name: 'Design Systems',
      responsibility:
        'Owns @nas/ui: tokens, atoms/molecules, registry accuracy, and token exceptions.',
    },
    {
      id: 'owner.control-plane',
      name: 'Control Plane',
      responsibility:
        'Owns apps/no-ai-slop: templates, pages, navigation, and page-level composition.',
    },
  ],

  tokens,

  components: [
    // ── @nas/ui atoms ────────────────────────────────────────────────────────
    {
      id: 'component.button',
      name: 'Button',
      atomicLevel: 'atom',
      category: 'input',
      purpose: 'Trigger exactly one action. The primary variant is the screen’s one accent.',
      sourcePath: 'packages/ui/src/components/primitives.tsx',
      composedOf: [],
      variants: [
        { name: 'primary', purpose: 'The single primary action of a screen (mint accent).' },
        { name: 'secondary', purpose: 'Supporting actions on a bordered surface.' },
        { name: 'ghost', purpose: 'Low-emphasis chrome actions.' },
        {
          name: 'compact',
          purpose:
            'Height modifier for secondary chrome controls (combines with ghost/secondary; never with primary).',
        },
      ],
      props: [
        {
          name: 'variant',
          type: "'primary' | 'secondary' | 'ghost'",
          required: false,
          description: 'Visual emphasis; defaults to secondary so primary is always deliberate.',
        },
        {
          name: 'children',
          type: 'ReactNode',
          required: true,
          description: 'The action label. Buttons always carry visible text.',
        },
      ],
      states: [
        { state: 'default', behavior: 'Resting fill per variant.' },
        { state: 'hover', behavior: 'Fill deepens via color.accent-hover / color.surface-2.' },
        { state: 'focus_visible', behavior: 'Token focus ring, offset outside the control.' },
        {
          state: 'disabled',
          behavior: 'opacity.disabled + not-allowed cursor; disabled attribute set.',
        },
      ],
      usesTokens: [
        'color.accent',
        'color.accent-hover',
        'color.on-accent',
        'color.surface',
        'color.surface-2',
        'color.text',
        'color.border',
        'type.weight.medium',
        'space.3',
        'space.4',
        'space.6',
        'radius.md',
        'border.width',
        'motion.fast',
        'motion.ease',
        'size.control',
        'size.control-compact',
        'opacity.disabled',
      ],
      followsPrinciples: ['principle.one-primary-action', 'principle.closed-scales'],
      accessibility: ['rule.focus-visible', 'rule.touch-target'],
      responsiveBehavior: 'Fixed height; width follows content. No breakpoint changes.',
      prohibitedUses: [
        'More than one primary variant rendered on a single screen',
        'Combining the compact modifier with the primary variant',
        'Using a button for pure navigation when a link communicates it better',
      ],
      requiredEvidence: ['test', 'accessibility_result'],
      ownerId: 'owner.design-systems',
      version: '1.1.0',
      status: 'stable',
      tests: ['packages/ui/src/components/components.test.tsx'],
    },
    {
      id: 'component.badge',
      name: 'Badge',
      atomicLevel: 'atom',
      category: 'feedback',
      purpose: 'Show a status as label + symbol + tone — the tone alone never carries meaning.',
      sourcePath: 'packages/ui/src/components/status.tsx',
      composedOf: [],
      variants: [
        { name: 'success', purpose: 'Verified / passing states.' },
        { name: 'warning', purpose: 'Documented concerns.' },
        { name: 'danger', purpose: 'Failures and blocked states.' },
        { name: 'info', purpose: 'Neutral verified facts (e.g. signature checks).' },
        { name: 'neutral', purpose: 'Not-tested / inert states.' },
      ],
      props: [
        { name: 'tone', type: 'StatusTone', required: true, description: 'Status color pair.' },
        { name: 'label', type: 'string', required: true, description: 'The visible text label.' },
        {
          name: 'symbol',
          type: 'string',
          required: false,
          description: 'Decorative glyph (aria-hidden); the label carries the meaning.',
        },
      ],
      states: [{ state: 'default', behavior: 'Static; badges are never interactive.' }],
      usesTokens: [
        'status.success.fg',
        'status.success.bg',
        'status.warning.fg',
        'status.warning.bg',
        'status.danger.fg',
        'status.danger.bg',
        'status.info.fg',
        'status.info.bg',
        'status.neutral.fg',
        'status.neutral.bg',
        'space.1',
        'space.2',
        'space.3',
        'radius.full',
        'type.size.xs',
        'type.weight.medium',
        'type.weight.semibold',
        'type.leading.normal',
      ],
      followsPrinciples: ['principle.status-not-color-alone'],
      accessibility: ['rule.status-not-color-alone', 'rule.contrast-aa'],
      responsiveBehavior: 'Inline pill; wraps with its line, never truncates its label.',
      prohibitedUses: [
        'Communicating status with tone alone (label or symbol is mandatory)',
        'Making a badge clickable — use a Button or link instead',
        'Metric-wall decoration: a badge must answer a decision question',
      ],
      requiredEvidence: ['test', 'accessibility_result'],
      ownerId: 'owner.design-systems',
      version: '1.1.0',
      status: 'stable',
      tests: ['packages/ui/src/components/components.test.tsx'],
    },
    // ── @nas/ui molecules ────────────────────────────────────────────────────
    {
      id: 'component.verdict-badge',
      name: 'VerdictBadge',
      atomicLevel: 'molecule',
      category: 'feedback',
      purpose: 'Map a TC-10 release verdict to the badge vocabulary (pass/warning/fail/blocked).',
      sourcePath: 'packages/ui/src/components/status.tsx',
      composedOf: ['component.badge'],
      variants: [],
      props: [
        {
          name: 'verdict',
          type: 'ReleaseVerdict',
          required: true,
          description: 'The signed gate verdict to display.',
        },
      ],
      states: [{ state: 'default', behavior: 'Static mapping via verdictMeta.' }],
      usesTokens: [],
      followsPrinciples: ['principle.status-not-color-alone', 'principle.evidence-backed'],
      accessibility: ['rule.status-not-color-alone'],
      responsiveBehavior: 'Inherits Badge.',
      prohibitedUses: ['Displaying a verdict that is not a real kernel output'],
      requiredEvidence: ['test'],
      ownerId: 'owner.design-systems',
      version: '1.1.0',
      status: 'stable',
      tests: ['packages/ui/src/components/components.test.tsx'],
    },
    {
      id: 'component.grade-badge',
      name: 'GradeBadge',
      atomicLevel: 'molecule',
      category: 'feedback',
      purpose: 'Map an anti-slop dimension grade to the badge vocabulary.',
      sourcePath: 'packages/ui/src/components/status.tsx',
      composedOf: ['component.badge'],
      variants: [],
      props: [
        {
          name: 'grade',
          type: 'Grade',
          required: true,
          description: 'pass | pass_with_concern | fail | not_tested.',
        },
      ],
      states: [{ state: 'default', behavior: 'Static mapping via gradeMeta.' }],
      usesTokens: [],
      followsPrinciples: ['principle.status-not-color-alone'],
      accessibility: ['rule.status-not-color-alone'],
      responsiveBehavior: 'Inherits Badge.',
      prohibitedUses: ['Collapsing multiple dimension grades into one badge'],
      requiredEvidence: ['test'],
      ownerId: 'owner.design-systems',
      version: '1.1.0',
      status: 'stable',
      tests: ['packages/ui/src/components/components.test.tsx'],
    },
    {
      id: 'component.card',
      name: 'Card',
      atomicLevel: 'molecule',
      category: 'layout',
      purpose: 'Group one topic (title, optional subtitle/action) on a bordered surface.',
      sourcePath: 'packages/ui/src/components/primitives.tsx',
      composedOf: [],
      variants: [],
      props: [
        { name: 'title', type: 'ReactNode', required: false, description: 'Card heading (h2).' },
        {
          name: 'subtitle',
          type: 'ReactNode',
          required: false,
          description: 'One-line qualifier under the title.',
        },
        {
          name: 'action',
          type: 'ReactNode',
          required: false,
          description: 'Trailing badge or control aligned with the title.',
        },
        { name: 'children', type: 'ReactNode', required: true, description: 'Card body.' },
      ],
      states: [{ state: 'default', behavior: 'Static surface; no hover elevation games.' }],
      usesTokens: [
        'color.surface',
        'color.border',
        'border.width',
        'radius.lg',
        'space.1',
        'space.4',
        'space.5',
        'space.7',
        'shadow.sm',
        'type.size.lg',
        'type.size.sm',
        'type.weight.semibold',
        'type.leading.tight',
        'color.text-secondary',
      ],
      followsPrinciples: ['principle.hierarchy-without-decoration', 'principle.radical-clarity'],
      accessibility: ['rule.contrast-aa'],
      responsiveBehavior: 'Fills its grid track; grids collapse via auto-fit at size.card-min.',
      prohibitedUses: [
        'Nesting cards inside cards',
        'Using a card as a click target (cards are containers, not buttons)',
      ],
      requiredEvidence: ['test', 'accessibility_result'],
      ownerId: 'owner.design-systems',
      version: '1.1.0',
      status: 'stable',
      tests: ['packages/ui/src/components/components.test.tsx'],
    },
    {
      id: 'component.page-header',
      name: 'PageHeader',
      atomicLevel: 'molecule',
      category: 'layout',
      purpose:
        'Open every screen with the same structure: eyebrow, single h1, measure-limited description, optional single action.',
      sourcePath: 'packages/ui/src/components/primitives.tsx',
      composedOf: [],
      variants: [],
      props: [
        {
          name: 'eyebrow',
          type: 'string',
          required: false,
          description: 'Uppercase context label above the title.',
        },
        { name: 'title', type: 'string', required: true, description: 'The one h1 per page.' },
        {
          name: 'description',
          type: 'string',
          required: false,
          description: 'What this screen answers, in one or two sentences.',
        },
        {
          name: 'action',
          type: 'ReactNode',
          required: false,
          description: 'The screen’s single primary action, when it has one.',
        },
      ],
      states: [{ state: 'default', behavior: 'Static header with bottom divider.' }],
      usesTokens: [
        'space.2',
        'space.6',
        'border.width',
        'color.border',
        'type.size.xs',
        'type.tracking.wide',
        'color.text-tertiary',
        'type.weight.medium',
        'type.size.2xl',
        'type.weight.semibold',
        'type.leading.tight',
        'type.tracking.tight',
        'color.text-secondary',
        'layout.measure-max',
      ],
      followsPrinciples: [
        'principle.radical-clarity',
        'principle.one-primary-action',
        'principle.hierarchy-without-decoration',
      ],
      accessibility: ['rule.single-h1'],
      responsiveBehavior: 'Title and action wrap on narrow viewports; description keeps measure.',
      prohibitedUses: [
        'More than one PageHeader per screen',
        'Placing multiple actions in the action slot',
      ],
      requiredEvidence: ['test', 'accessibility_result'],
      ownerId: 'owner.design-systems',
      version: '1.1.0',
      status: 'stable',
      tests: ['packages/ui/src/components/components.test.tsx'],
    },
    {
      id: 'component.key-value',
      name: 'KeyValue',
      atomicLevel: 'molecule',
      category: 'data_display',
      purpose: 'Present attributable facts (build ids, digests, commits) as a definition list.',
      sourcePath: 'packages/ui/src/components/primitives.tsx',
      composedOf: [],
      variants: [],
      props: [
        {
          name: 'items',
          type: 'KeyValueItem[]',
          required: true,
          description: 'Label/value pairs; values may embed badges or mono spans.',
        },
      ],
      states: [{ state: 'default', behavior: 'Two-column grid; values wrap anywhere (digests).' }],
      usesTokens: ['space.3', 'space.6', 'color.text-secondary', 'type.size.sm', 'size.label-min'],
      followsPrinciples: ['principle.evidence-backed', 'principle.radical-clarity'],
      accessibility: ['rule.contrast-aa'],
      responsiveBehavior: 'Grid keeps a min label column; long values wrap, never overflow.',
      prohibitedUses: ['Free-form prose in values — facts only'],
      requiredEvidence: ['test'],
      ownerId: 'owner.design-systems',
      version: '1.1.0',
      status: 'stable',
      tests: ['packages/ui/src/components/components.test.tsx'],
    },
    {
      id: 'component.reason-list',
      name: 'ReasonList',
      atomicLevel: 'molecule',
      category: 'data_display',
      purpose:
        'List reasons/findings with a leading status and an EXPLICIT empty state — never a blank void.',
      sourcePath: 'packages/ui/src/components/primitives.tsx',
      composedOf: [],
      variants: [],
      props: [
        {
          name: 'items',
          type: '{ key; leading?; primary; secondary? }[]',
          required: true,
          description: 'Reasons with optional leading badge and secondary mono detail.',
        },
        {
          name: 'emptyLabel',
          type: 'string',
          required: true,
          description: 'REQUIRED text shown when there are zero items.',
        },
      ],
      states: [
        { state: 'default', behavior: 'Divided rows with leading status element.' },
        { state: 'empty', behavior: 'Renders emptyLabel as muted text — mandatory prop.' },
      ],
      usesTokens: [
        'space.1',
        'space.3',
        'space.4',
        'border.width',
        'color.border',
        'color.text-secondary',
        'type.family.mono',
        'type.size.sm',
      ],
      followsPrinciples: ['principle.explicit-states', 'principle.evidence-backed'],
      accessibility: ['rule.contrast-aa'],
      responsiveBehavior: 'Rows stack their secondary detail under the primary on any width.',
      prohibitedUses: ['Omitting emptyLabel semantics by passing a decorative placeholder'],
      requiredEvidence: ['test'],
      ownerId: 'owner.design-systems',
      version: '1.1.0',
      status: 'stable',
      tests: ['packages/ui/src/components/components.test.tsx'],
    },
    {
      id: 'component.theme-toggle',
      name: 'ThemeToggle',
      atomicLevel: 'molecule',
      category: 'input',
      purpose:
        'Switch light/dark explicitly; defaults to the OS preference until the user chooses.',
      sourcePath: 'packages/ui/src/components/ThemeToggle.tsx',
      composedOf: ['component.button'],
      variants: [],
      props: [],
      states: [
        { state: 'default', behavior: 'Shows the theme it will switch TO, with an aria-label.' },
        { state: 'hover', behavior: 'Ghost-button hover surface.' },
        { state: 'focus_visible', behavior: 'Token focus ring.' },
      ],
      usesTokens: ['size.control-compact', 'space.4'],
      followsPrinciples: ['principle.closed-scales'],
      accessibility: ['rule.focus-visible'],
      responsiveBehavior: 'Compact ghost button; identical at all widths.',
      prohibitedUses: ['Auto-switching the theme without an explicit user action'],
      requiredEvidence: ['browser_run'],
      ownerId: 'owner.design-systems',
      version: '1.1.0',
      status: 'stable',
      tests: ['apps/no-ai-slop/e2e/browser-check.mjs'],
    },
    // ── Control-plane organisms / templates / pages ──────────────────────────
    {
      id: 'component.nav-links',
      name: 'NavLinks',
      atomicLevel: 'organism',
      category: 'navigation',
      purpose:
        'Primary navigation listing only screens that exist; marks the current page for AT via aria-current.',
      sourcePath: 'apps/no-ai-slop/app/components/NavLinks.tsx',
      composedOf: [],
      variants: [],
      props: [],
      states: [
        { state: 'default', behavior: 'Vertical list (desktop), wrapping row (below desktop).' },
        { state: 'hover', behavior: 'surface-2 hover fill.' },
        { state: 'active', behavior: 'Current page gets surface-2 fill + aria-current="page".' },
        { state: 'focus_visible', behavior: 'Token focus ring.' },
      ],
      usesTokens: [
        'space.1',
        'space.2',
        'space.3',
        'space.4',
        'radius.md',
        'color.text-secondary',
        'color.text',
        'color.surface-2',
        'type.size.sm',
        'type.weight.medium',
      ],
      followsPrinciples: ['principle.radical-clarity'],
      accessibility: ['rule.aria-current-nav', 'rule.focus-visible'],
      responsiveBehavior: 'Column in the sidebar; wraps horizontally under the top bar < 1024px.',
      prohibitedUses: ['Nav items for screens that do not exist yet'],
      requiredEvidence: ['browser_run', 'accessibility_result'],
      ownerId: 'owner.control-plane',
      version: '1.1.0',
      status: 'stable',
      tests: ['apps/no-ai-slop/e2e/browser-check.mjs'],
    },
    {
      id: 'component.app-shell',
      name: 'AppShell',
      atomicLevel: 'template',
      category: 'layout',
      purpose:
        'The one persistent structure: brand + theme control + navigation beside a measured main column.',
      sourcePath: 'apps/no-ai-slop/app/components/AppShell.tsx',
      composedOf: ['component.nav-links', 'component.theme-toggle'],
      variants: [],
      props: [
        { name: 'children', type: 'ReactNode', required: true, description: 'The page content.' },
      ],
      states: [
        { state: 'default', behavior: 'Sticky sidebar (desktop) / static top bar (mobile).' },
      ],
      usesTokens: [
        'layout.sidebar-width',
        'layout.content-max',
        'border.width',
        'color.border',
        'color.surface',
        'space.4',
        'space.5',
        'space.6',
        'space.9',
        'type.weight.semibold',
        'type.size.lg',
        'type.tracking.tight',
        'breakpoint.desktop',
      ],
      followsPrinciples: ['principle.radical-clarity', 'principle.hierarchy-without-decoration'],
      accessibility: ['rule.focus-visible'],
      responsiveBehavior:
        'Structure adapts: sidebar becomes a top bar below breakpoint.desktop instead of shrinking.',
      prohibitedUses: ['Rendering a page outside the shell'],
      requiredEvidence: ['browser_run', 'accessibility_result', 'screenshot'],
      ownerId: 'owner.control-plane',
      version: '1.1.0',
      status: 'stable',
      tests: ['apps/no-ai-slop/e2e/browser-check.mjs'],
    },
    {
      id: 'component.page-overview',
      name: 'OverviewPage',
      atomicLevel: 'page',
      category: 'data_display',
      purpose: 'Answer: is this build ready, and what proves it? Entry point to the decision.',
      sourcePath: 'apps/no-ai-slop/app/page.tsx',
      composedOf: [
        'component.app-shell',
        'component.page-header',
        'component.card',
        'component.key-value',
        'component.badge',
        'component.verdict-badge',
      ],
      variants: [],
      props: [],
      states: [
        { state: 'default', behavior: 'Renders real kernel output for the sample lifecycle.' },
      ],
      usesTokens: ['space.6', 'space.8', 'size.card-min'],
      followsPrinciples: [
        'principle.radical-clarity',
        'principle.one-primary-action',
        'principle.evidence-backed',
      ],
      accessibility: ['rule.single-h1'],
      responsiveBehavior: 'Card grid auto-fits at size.card-min; single column on mobile.',
      prohibitedUses: ['Adding metrics that do not change a release decision'],
      requiredEvidence: ['browser_run', 'accessibility_result', 'screenshot'],
      ownerId: 'owner.control-plane',
      version: '1.1.0',
      status: 'stable',
      tests: ['apps/no-ai-slop/e2e/browser-check.mjs'],
    },
    {
      id: 'component.page-release',
      name: 'ReleasePage',
      atomicLevel: 'page',
      category: 'data_display',
      purpose:
        'Show the signed staging + production decisions with exact blocking reasons and every dimension grade.',
      sourcePath: 'apps/no-ai-slop/app/release/page.tsx',
      composedOf: [
        'component.app-shell',
        'component.page-header',
        'component.card',
        'component.key-value',
        'component.reason-list',
        'component.badge',
        'component.verdict-badge',
        'component.grade-badge',
      ],
      variants: [],
      props: [],
      states: [
        { state: 'default', behavior: 'Real TC-10 decisions; blocked production shown honestly.' },
        { state: 'empty', behavior: 'ReasonList renders explicit empty labels for zero reasons.' },
      ],
      usesTokens: ['space.1', 'space.3', 'space.8', 'type.size.base', 'type.size.sm'],
      followsPrinciples: ['principle.evidence-backed', 'principle.explicit-states'],
      accessibility: ['rule.single-h1'],
      responsiveBehavior: 'Cards stack; key-value values wrap digests on narrow screens.',
      prohibitedUses: ['Hiding a blocking reason behind an aggregate'],
      requiredEvidence: ['browser_run', 'accessibility_result', 'screenshot'],
      ownerId: 'owner.control-plane',
      version: '1.1.0',
      status: 'stable',
      tests: ['apps/no-ai-slop/e2e/browser-check.mjs'],
    },
    {
      id: 'component.page-evidence',
      name: 'EvidencePage',
      atomicLevel: 'page',
      category: 'data_display',
      purpose: 'Show the sealed TC-17 chain in order, with digests, and its live verification.',
      sourcePath: 'apps/no-ai-slop/app/evidence/page.tsx',
      composedOf: [
        'component.app-shell',
        'component.page-header',
        'component.card',
        'component.badge',
      ],
      variants: [],
      props: [],
      states: [
        { state: 'default', behavior: 'Chain records in sequence with kind labels + digests.' },
        {
          state: 'error',
          behavior: 'Header badge flips to "Chain invalid" when verification fails.',
        },
      ],
      usesTokens: ['space.1', 'space.3', 'space.8', 'type.size.xs'],
      followsPrinciples: ['principle.evidence-backed', 'principle.progressive-disclosure'],
      accessibility: ['rule.single-h1'],
      responsiveBehavior: 'Digests truncate with ellipsis; summaries wrap.',
      prohibitedUses: ['Rendering evidence that failed signature verification as valid'],
      requiredEvidence: ['browser_run', 'accessibility_result', 'screenshot'],
      ownerId: 'owner.control-plane',
      version: '1.1.0',
      status: 'stable',
      tests: ['apps/no-ai-slop/e2e/browser-check.mjs'],
    },
    {
      id: 'component.page-system',
      name: 'SystemPage',
      atomicLevel: 'page',
      category: 'data_display',
      purpose:
        'Answer: is the product system itself coherent? Renders the live registry validation, tokens, components, patterns, architecture check, and exceptions.',
      sourcePath: 'apps/no-ai-slop/app/system/page.tsx',
      composedOf: [
        'component.app-shell',
        'component.page-header',
        'component.card',
        'component.key-value',
        'component.reason-list',
        'component.badge',
      ],
      variants: [],
      props: [],
      states: [
        { state: 'default', behavior: 'Live validateDesignSystemRegistry + architecture check.' },
        {
          state: 'error',
          behavior: 'Validation problems render as danger findings, never hidden.',
        },
        { state: 'empty', behavior: 'Zero-violation lists state that explicitly.' },
      ],
      usesTokens: [
        'space.1',
        'space.3',
        'space.6',
        'space.8',
        'size.card-min',
        'type.size.base',
        'type.size.sm',
      ],
      followsPrinciples: [
        'principle.progressive-disclosure',
        'principle.evidence-backed',
        'principle.explicit-states',
      ],
      accessibility: ['rule.single-h1', 'rule.focus-visible'],
      responsiveBehavior: 'Disclosure sections stack; token tables scroll inside their region.',
      prohibitedUses: ['Turning the registry into a decorative component gallery'],
      requiredEvidence: ['browser_run', 'accessibility_result', 'screenshot'],
      ownerId: 'owner.control-plane',
      version: '1.1.0',
      status: 'stable',
      tests: ['apps/no-ai-slop/e2e/browser-check.mjs'],
    },
  ],

  patterns: [
    {
      id: 'pattern.status-badge',
      name: 'Status vocabulary',
      kind: 'functional',
      purpose: 'One shared mapping from verdicts/grades to label + symbol + tone.',
      consistsOf: ['component.badge', 'component.verdict-badge', 'component.grade-badge'],
      usesTokens: [],
      conditionsOfUse:
        'Any status shown anywhere uses this vocabulary; new statuses extend the mapping, never invent ad-hoc colors.',
    },
    {
      id: 'pattern.one-primary-action',
      name: 'One primary action',
      kind: 'functional',
      purpose: 'Each screen exposes at most one accent action, usually in the PageHeader slot.',
      consistsOf: ['component.page-header', 'component.button'],
      usesTokens: ['color.accent'],
      conditionsOfUse: 'Screens with no dominant action render no primary button at all.',
    },
    {
      id: 'pattern.explicit-empty-state',
      name: 'Explicit empty state',
      kind: 'functional',
      purpose: 'Zero-item lists say so in words instead of rendering a void.',
      consistsOf: ['component.reason-list'],
      usesTokens: [],
      conditionsOfUse: 'Every list that can be empty must supply a meaningful emptyLabel.',
    },
    {
      id: 'pattern.evidence-reference',
      name: 'Evidence reference',
      kind: 'functional',
      purpose: 'Material claims render alongside their digest / evidence identifier in mono.',
      consistsOf: ['component.key-value', 'component.reason-list'],
      usesTokens: ['type.family.mono'],
      conditionsOfUse: 'Applies to builds, checks, decisions, and any "verified" claim.',
    },
    {
      id: 'pattern.card-grid',
      name: 'Card grid',
      kind: 'perceptual',
      purpose: 'Summary cards in a responsive auto-fit grid that collapses to one column.',
      consistsOf: ['component.card'],
      usesTokens: ['size.card-min', 'space.6'],
      conditionsOfUse: 'Use for peer summaries only; never for a wall of vanity metrics.',
    },
    {
      id: 'pattern.progressive-disclosure',
      name: 'Progressive disclosure',
      kind: 'functional',
      purpose:
        'Conclusions render first; full inventories (tokens, records) expand behind a native disclosure.',
      consistsOf: ['component.card'],
      usesTokens: [],
      conditionsOfUse:
        'Detail must remain reachable by keyboard (native <details>/<summary>) and never hide failures.',
    },
  ],

  accessibilityRules: [
    {
      id: 'rule.focus-visible',
      requirement: 'Every interactive element shows a visible focus indicator.',
      wcagCriterion: '2.4.7',
      verification: 'base.css :focus-visible tokens + e2e/browser-check.mjs axe scans.',
    },
    {
      id: 'rule.touch-target',
      requirement:
        'Interactive controls are at least size.control (40px) tall; compact (36px) only for secondary chrome.',
      wcagCriterion: '2.5.8',
      verification: 'base.css control tokens + registry raw-value audit.',
    },
    {
      id: 'rule.contrast-aa',
      requirement: 'Text meets 4.5:1 and UI accents 3:1 in both themes.',
      wcagCriterion: '1.4.3',
      verification: 'packages/ui/src/tokens.test.ts contrast assertions.',
    },
    {
      id: 'rule.status-not-color-alone',
      requirement: 'Status is conveyed by label/symbol plus tone, never tone alone.',
      wcagCriterion: '1.4.1',
      verification: 'packages/ui/src/components/components.test.tsx badge assertions.',
    },
    {
      id: 'rule.reduced-motion',
      requirement: 'All animation and transitions collapse under prefers-reduced-motion.',
      wcagCriterion: '2.3.3',
      verification: 'base.css reduced-motion block.',
    },
    {
      id: 'rule.aria-current-nav',
      requirement: 'The current page is marked with aria-current="page" in primary navigation.',
      verification: 'NavLinks implementation + e2e/browser-check.mjs.',
    },
    {
      id: 'rule.single-h1',
      requirement: 'Every screen renders exactly one h1.',
      verification: 'e2e/browser-check.mjs structure assertion on every route.',
    },
  ],

  exceptions: [
    {
      id: 'exception.breakpoint-media-query',
      scope: 'packages/ui/src/base.css::1023px',
      rationale:
        'CSS media queries cannot read custom properties, so the responsive switch hard-codes (breakpoint.desktop - 1)px. The value is mirror-tested against breakpoint.desktop in registry.test.ts.',
      ownerId: 'owner.design-systems',
      expiresAt: '2027-06-30T00:00:00.000Z',
      remediation:
        'Replace with CSS custom media / env() once baseline browser support lands; until then the mirror test prevents drift.',
    },
  ],
};
